package com.autonomousgames.starcycle.core.screens;

public enum ScreenType {
	SPLASH, MAINMENU, STARTMENU, ABOUT, SETTINGS, 
	MULTIPLAYER, SINGLEPLAYER, TUTORIAL,
	TUTORIAL1, TUTORIAL2, TUTORIAL3, TUTORIAL4,
	TUTORIAL5, TUTORIAL6, TUTORIAL7, TUTORIAL8,
	CAMPAIGNSELECT, MULTIPLAYERSELECT
}
